### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by cubarro** [joaohenry23/GOES#4]
In almost all notebooks I get similar messages like this:

`FileNotFoundError: [Errno 2] No such file or directory: '/home/joao/Downloads/OR_ABI-L2-CMIPF-M6C13_G16_s20200802030177_e20200802039497_c20200802039590.nc'`

**Comment by cubarro** [comment]
I feel sorry.
There is no error at al.
I understood that I have to change variable to my own download directory..

**Comment by joaohenry23** [comment]
Yes, you must write the path where the netcdf file is located on your computer, in the tutorials I use the path of my computer.
